name: PKUAutoSubmit

on:
  schedule:
    - cron: '58 0 * * 1'
    - cron: '43 0 * * 2'
    - cron: '33 0 * * 3'
    - cron: '43 0 * * 4'
    - cron: '46 1 * * 5'
    - cron: '34 2 * * 6'
    - cron: '58 1 * * 0'
    
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v2
        
      - name: 'Set up Python'
        uses: actions/setup-python@v1
        with:
           python-version: 3.7
           
      - name: 'Install requirements'
        run: 
          pip install selenium
        
      - name: 'Working'
        run:
          python main.py --ID ${{secrets.ID}} --PASSWORD ${{secrets.PASSWORD}}
